name: Build-WASM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev && rustup target add wasm32-unknown-unknown
      - name: Build WASM
        run: cargo build --release --target wasm32-unknown-unknown
